language: node_js
node_js: '12'
cache: yarn
jobs:
  include:
  - stage: build
    script: yarn build
deploy:
  provider: s3
  access_key_id: AKIARRT74VEDFMGTFYSA
  bucket: vanbujm-sas-deploy-bucket
  skip_cleanup: true
  local_dir: dist
  on:
    repo: vanbujm/sas-backend
  secret_access_key:
    secure: YtEre4IxR75JMpXLhSCa1Fxx59wO25wrryf/oUd3oa/1S3e9hle8yXzT7vqMXCgTkSmSYAmuR96lZaFdTpUeJS+rhdrpDl4uherupR5mHp/QYZJoj8ioULkJDvINWvbC0bQM8TG2p/jhdm3p6ubDNG99EREevhzj8QQLouoq6XJWZGP1ypkAFx2TvxPOUgvqUXOULfC64QDiqx5L/xIxIlfWliteuI0tMaBeEdUdBYw6k2o5s7YJE5zmqFV73+l9lry9TpJxO7FjJV3B1Y4r4GSkBlUPoeDsaKUB7y8pdWY2KWeDOc8+FCqrcLepbeDEK6rqNsxjPMx9coC0loaGmf1/AgBU7ZiDlgQSikB0YxWK5WkQKf2c8678Ej+94ACUjF8Gv7wYiLhEo+7+sliU2V4cLNx21EWEZfYq7OYDpqF4YjRNI4ILtNq+JTbs+82J4fz7iXraM9XVdsanIwdXFL2q2lrakeaGrN9Dk+yob3bAJqjabrUOsHA8toWcXh+IDKQOd4xb9ShkTQiUrr/Ca0qo7/0u0JGVu26EmoE/oyVyieww9fyFZaX+hY4FlyhxcLLX+YIa/EQbSQRxfjF3zILqouEZG1dAHMPXM7WKt8qLgqJYdHfLXj6CSbakg72QeLI/FL5Hfy2HvvoxLkftO1js9gDDM0lWYIS+vT3KlWw=
